### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ShreyashSomvanshi2** [ShreyashSomvanshi/simple-contact-form#5]
Add favicon

trying out git issues.

**Comment by ShreyashSomvanshi2** [comment]
Please add font-awesome (fa) icons under submit button such as LinkedIn icon, Mailbox icon, Twitter, Instagram, Facebook icons , etc. @ShreyashSomvanshi

**Comment by ShreyashSomvanshi** [comment]
> 

Ok
